apiVersion: apps/v1
kind: Deployment
metadata:
  name: hangman-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hangman
  template:
    metadata:
      labels:
        app: hangman
    spec:
      volumes: 
      - name: hangman-data
        persistentVolumeClaim:
          claimName: hangman-pvc1
      containers:
      - name: hangman-container
        image: whalerider02/hangman-app-mp:final
        imagePullPolicy: Always
        ports:
        - containerPort: 5200
        volumeMounts:
        - name: hangman-data
          mountPath: /mnt/azure # Corrected mount path
        resources: 
          limits:
            cpu: "200m"
            memory: "256Mi"
