apiVersion: apps/v1
kind: Deployment
metadata:
  name: hangman-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hangman
  template:
    metadata:
      labels:
        app: hangman
    spec:
      containers:
      - name: hangman-container
        image: whalerider02/hangman-app-mp
        ports:
        - containerPort: 5200
        resources:
          limits:
            cpu: "200m"   # Limit to 200 millicores of CPU
            memory: "256Mi" # Limit to 256 MB of memory
