apiVersion: apps/v1
kind: Deployment
metadata:
  name: hangman-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hangman
  template:
    metadata:
      labels:
        app: hangman
    spec:
      volumes:  # Define volumes here at the top level
      - name: hangman-data
        persistentVolumeClaim:
          claimName: hangman-pvc
      containers:
      - name: hangman-container
        image: whalerider02/hangman-app:latest  
        ports:
        - containerPort: 5200
        volumeMounts:
        - name: hangman-data
          mountPath: /app/player_data.json 
        resources: 
          limits:
            cpu: "200m"   
            memory: "256Mi" 