apiVersion: v1
kind: PersistentVolume
metadata:
  name: hangman-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # Keep the data even when the PV is deleted
  gcePersistentDisk:
    pdName: hangman-pv  # Replace with the name of your Persistent Disk 
    fsType: ext4 # Or your desired filesystem