apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hangman-pvc1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  volumeName: hangman-pv
  storageClassName: managed-csi