apiVersion: v1
kind: Service
metadata:
  name: hangman-service
spec:
  type: NodePort # You can use 'NodePort' if 'LoadBalancer' is not available
  selector:
    app: hangman
  ports:
  - protocol: TCP
    port: 5000  # Use the same port as the container
    targetPort: 5000